export const GET_DELIVERY_DETAILS = "GET_DELIVERY_DETAILS";
export const ADD_ITEM = "ADD_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const PAYMENT_INFO = "PAYMENT_INFO";
